apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-freeradiusdb
  namespace: freeradius
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /PATH/freeradiusdb
    server: IP DO SERVIDOR
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-freeradiusdb
  namespace: freeradius
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 10Gi