apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-freeradius
  namespace: freeradius
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfsroot/kubernetes/freeradius
    server: 10.10.67.24
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-freeradius
  namespace: freeradius
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 10Gi